"""
URL configuration for python_learning project.
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('assignment1/', include('assignment1.urls')),
    path('assignment2/', include('assignment2.urls')),
    path('assignment3/', include('assignment3.urls')),
    path('assignment4/', include('assignment4.urls')),
    path('assignment5/', include('assignment5.urls')),
    path('assignment6/', include('assignment6.urls')),
    path('assignment7/', include('assignment7.urls')),
    path('assignment8/', include('assignment8.urls')),
    path('assignment9/', include('assignment9.urls')),
    path('assignment10/', include('assignment10.urls')),
    path('assignment11/', include('assignment11.urls')),
    path('assignment12/', include('assignment12.urls')),
    path('assignment13/', include('assignment13.urls')),
    path('assignment14/', include('assignment14.urls')),
    path('assignment15/', include('assignment15.urls')),
    path('assignment16/', include('assignment16.urls')),
    path('assignment17/', include('assignment17.urls')),
    path('assignment18/', include('assignment18.urls')),
    path('assignment19/', include('assignment19.urls')),
    path('assignment20/', include('assignment20.urls')),
    path('assignment21/', include('assignment21.urls')),
    path('assignment22/', include('assignment22.urls')),
    path('assignment23/', include('assignment23.urls')),
    path('assignment24/', include('assignment24.urls')),
    path('assignment25/', include('assignment25.urls')),
    path('assignment26/', include('assignment26.urls')),
    path('assignment27/', include('assignment27.urls')),
    path('assignment28/', include('assignment28.urls')),
    path('assignment29/', include('assignment29.urls')),
    path('assignment30/', include('assignment30.urls')),
    path('assignment31/', include('assignment31.urls')),
    path('assignment32/', include('assignment32.urls')),
    path('assignment33/', include('assignment33.urls')),
    path('assignment34/', include('assignment34.urls')),
    path('assignment35/', include('assignment35.urls')),
    path('assignment36/', include('assignment36.urls')),
    path('assignment37/', include('assignment37.urls')),
    path('assignment38/', include('assignment38.urls')),
    path('assignment39/', include('assignment39.urls')),
    path('assignment40/', include('assignment40.urls')),
    path('assignment41/', include('assignment41.urls')),
    path('assignment42/', include('assignment42.urls')),
    path('assignment43/', include('assignment43.urls')),
]
